#include "win32.h"
#include "process.h"
#include "../include/network.h"
#include "../include/memory.h"
#include "../include/task.h"
#include "../string.h"

#define INTERNET_BASE 0x7D000000U
#define INTERNET_SLOTS 16U
#define INTERNET_DOWNLOAD_MAX (1024U*1024U)
#define ERROR_INTERNET_CANNOT_CONNECT 12029U
#define ERROR_INTERNET_INVALID_URL 12005U
typedef enum{INET_NONE,INET_SESSION,INET_CONNECTION,INET_REQUEST}inet_kind_t;
typedef struct{bool used;inet_kind_t kind;uint32_t owner;void*parent;uint16_t port;bool secure;char host[128],path[384],method[12];uint8_t*data;uint32_t size,position,status;}inet_handle_t;
static inet_handle_t handles[INTERNET_SLOTS];
static bool equal(const char*a,const char*b){if(!a||!b)return false;while(*a&&*b&&*a==*b){a++;b++;}return *a==*b;}
static inet_handle_t*from_handle(void*handle){uint32_t value=(uint32_t)(uintptr_t)handle;if(value<INTERNET_BASE||value>=INTERNET_BASE+INTERNET_SLOTS)return NULL;value-=INTERNET_BASE;return handles[value].used&&handles[value].owner==task_current_process_id()?&handles[value]:NULL;}
static void*allocate(inet_kind_t kind){for(uint32_t i=0;i<INTERNET_SLOTS;i++)if(!handles[i].used){kmemset(&handles[i],0,sizeof(handles[i]));handles[i].used=true;handles[i].kind=kind;handles[i].owner=task_current_process_id();return(void*)(uintptr_t)(INTERNET_BASE+i);}return NULL;}
static void*WIN32_API inet_InternetOpenA(const char*agent UNUSED,uint32_t access UNUSED,const char*proxy UNUSED,const char*bypass UNUSED,uint32_t flags UNUSED){return allocate(INET_SESSION);}
static bool split_url(const char*url,bool*secure,char*host,uint32_t host_size,char*path,uint32_t path_size,uint16_t*port){const char*p;uint32_t h=0;if(!url)return false;if(kstrncmp(url,"http://",7)==0){*secure=false;p=url+7;*port=80;}else if(kstrncmp(url,"https://",8)==0){*secure=true;p=url+8;*port=443;}else return false;while(*p&&*p!='/'&&*p!=':'&&h+1U<host_size)host[h++]=*p++;host[h]=0;if(*p==':'){uint32_t value=0;p++;while(*p>='0'&&*p<='9'){value=value*10U+(uint32_t)(*p-'0');p++;}if(value&&value<=65535U)*port=(uint16_t)value;}if(!*p)kstrcpy(path,"/");else{kstrncpy(path,p,path_size-1U);path[path_size-1U]=0;}return host[0]!=0;}
static bool download(inet_handle_t*request,const char*url){int32_t received;request->data=(uint8_t*)kmalloc(INTERNET_DOWNLOAD_MAX);if(!request->data)return false;received=request->secure?network_https_get(url,request->data,INTERNET_DOWNLOAD_MAX,15000U):network_http_get(url,request->data,INTERNET_DOWNLOAD_MAX,15000U);if(received<0){kfree(request->data);request->data=NULL;request->status=0;win32_process_set_last_error(ERROR_INTERNET_CANNOT_CONNECT);return false;}request->size=(uint32_t)received;request->position=0;request->status=200;return true;}
static void*WIN32_API inet_InternetOpenUrlA(void*session,const char*url,const char*headers UNUSED,uint32_t headers_length UNUSED,uint32_t flags UNUSED,uint32_t context UNUSED){inet_handle_t*parent=from_handle(session);void*handle;inet_handle_t*request;bool secure;uint16_t port;char host[128],path[384];if(!parent||parent->kind!=INET_SESSION||!split_url(url,&secure,host,sizeof(host),path,sizeof(path),&port)){win32_process_set_last_error(ERROR_INTERNET_INVALID_URL);return NULL;}handle=allocate(INET_REQUEST);if(!handle)return NULL;request=from_handle(handle);request->parent=session;request->secure=secure;request->port=port;kstrcpy(request->host,host);kstrcpy(request->path,path);kstrcpy(request->method,"GET");if(!download(request,url)){kmemset(request,0,sizeof(*request));return NULL;}return handle;}
static void*WIN32_API inet_InternetConnectA(void*session,const char*server,uint16_t port,const char*user UNUSED,const char*password UNUSED,uint32_t service UNUSED,uint32_t flags,uint32_t context UNUSED){inet_handle_t*parent=from_handle(session);void*handle;inet_handle_t*connection;if(!parent||parent->kind!=INET_SESSION||!server)return NULL;handle=allocate(INET_CONNECTION);if(!handle)return NULL;connection=from_handle(handle);connection->parent=session;connection->port=port?port:((flags&0x00800000U)?443U:80U);connection->secure=(flags&0x00800000U)!=0U;kstrncpy(connection->host,server,sizeof(connection->host)-1U);return handle;}
static void*WIN32_API inet_HttpOpenRequestA(void*connection,const char*verb,const char*object,const char*version UNUSED,const char*referrer UNUSED,const char**accept UNUSED,uint32_t flags,uint32_t context UNUSED){inet_handle_t*parent=from_handle(connection);void*handle;inet_handle_t*request;if(!parent||parent->kind!=INET_CONNECTION)return NULL;handle=allocate(INET_REQUEST);if(!handle)return NULL;request=from_handle(handle);request->parent=connection;request->secure=parent->secure||(flags&0x00800000U)!=0U;request->port=parent->port;kstrcpy(request->host,parent->host);kstrncpy(request->path,object&&*object?object:"/",sizeof(request->path)-1U);kstrncpy(request->method,verb&&*verb?verb:"GET",sizeof(request->method)-1U);return handle;}
static int WIN32_API inet_HttpSendRequestA(void*handle,const char*headers UNUSED,uint32_t headers_length UNUSED,const void*optional UNUSED,uint32_t optional_length UNUSED){inet_handle_t*request=from_handle(handle);char url[540];uint32_t used;if(!request||request->kind!=INET_REQUEST)return 0;kstrcpy(url,request->secure?"https://":"http://");kstrcat(url,request->host);used=(uint32_t)kstrlen(url);if((request->secure&&request->port!=443U)||(!request->secure&&request->port!=80U)){char rev[6];uint32_t n=0,p=request->port;url[used++]=':';do{rev[n++]=(char)('0'+p%10U);p/=10U;}while(p);while(n)url[used++]=rev[--n];url[used]=0;}if(kstrlen(url)+kstrlen(request->path)>=sizeof(url))return 0;kstrcat(url,request->path);return download(request,url)?1:0;}
static int WIN32_API inet_InternetReadFile(void*handle,void*buffer,uint32_t bytes,uint32_t*read){inet_handle_t*request=from_handle(handle);uint32_t available,take;if(read)*read=0;if(!request||request->kind!=INET_REQUEST||(!buffer&&bytes))return 0;available=request->position<request->size?request->size-request->position:0;take=bytes<available?bytes:available;if(take)kmemcpy(buffer,request->data+request->position,take);request->position+=take;if(read)*read=take;return 1;}
static int WIN32_API inet_InternetQueryDataAvailable(void*handle,uint32_t*available,uint32_t flags UNUSED,uint32_t context UNUSED){inet_handle_t*request=from_handle(handle);if(!request||!available)return 0;*available=request->position<request->size?request->size-request->position:0;return 1;}
static int WIN32_API inet_HttpQueryInfoA(void*handle,uint32_t level,void*buffer,uint32_t*length,uint32_t*index UNUSED){inet_handle_t*request=from_handle(handle);const char*status="200";if(!request||!buffer||!length)return 0;if((level&0xFFFFU)==19U&&(level&0x20000000U)){if(*length<4U){*length=4U;return 0;}*(uint32_t*)buffer=request->status;*length=4U;return 1;}if(*length<4U){*length=4U;return 0;}kstrcpy((char*)buffer,status);*length=3U;return 1;}
static int WIN32_API inet_InternetCloseHandle(void*handle){inet_handle_t*item=from_handle(handle);if(!item)return 0;if(item->data)kfree(item->data);kmemset(item,0,sizeof(*item));return 1;}
static int WIN32_API inet_InternetSetOptionA(void*handle UNUSED,uint32_t option UNUSED,void*buffer UNUSED,uint32_t length UNUSED){return 1;}
static int WIN32_API inet_InternetQueryOptionA(void*handle UNUSED,uint32_t option UNUSED,void*buffer UNUSED,uint32_t*length UNUSED){return 0;}
static int WIN32_API inet_InternetGetConnectedState(uint32_t*flags,uint32_t reserved UNUSED){net_info_t info;network_get_info(&info);if(flags)*flags=info.configured?1U:0U;return info.configured&&info.link_up;}
static uint32_t WIN32_API inet_InternetAttemptConnect(uint32_t reserved UNUSED){return inet_InternetGetConnectedState(NULL,0)?0U:ERROR_INTERNET_CANNOT_CONNECT;}
void win32_wininet_cleanup_process(uint32_t owner){for(uint32_t i=0;i<INTERNET_SLOTS;i++)if(handles[i].used&&handles[i].owner==owner){if(handles[i].data)kfree(handles[i].data);kmemset(&handles[i],0,sizeof(handles[i]));}}
uint32_t win32_wininet_resolve(const char*name){
#define I(api) if(equal(name,#api))return(uint32_t)(uintptr_t)&inet_##api
 I(InternetOpenA);I(InternetOpenUrlA);I(InternetConnectA);I(HttpOpenRequestA);I(HttpSendRequestA);I(InternetReadFile);I(InternetQueryDataAvailable);I(HttpQueryInfoA);I(InternetCloseHandle);I(InternetSetOptionA);I(InternetQueryOptionA);I(InternetGetConnectedState);I(InternetAttemptConnect);
#undef I
 return 0;
}
