typedef unsigned long DWORD;typedef long LONG;typedef unsigned short WORD;typedef unsigned char BYTE;typedef int BOOL;typedef void*HANDLE;typedef unsigned long SOCKET;
#define WINAPI __attribute__((stdcall))
#define STD_OUTPUT_HANDLE ((DWORD)-11)
typedef struct{WORD version,high;char description[257],status[129];WORD max_sockets,max_udp;char*vendor;}WSADATA32;
typedef struct{WORD family,port;BYTE address[4],zero[8];}SOCKADDR32;
typedef struct{DWORD low,high;}FILETIME32;typedef struct{WORD year,month,dow,day,hour,minute,second,milliseconds;}SYSTEMTIME32;
typedef struct{DWORD size,flags,fourcc,rgb_bits,r_mask,g_mask,b_mask,a_mask;}PIXELFORMAT;
typedef struct{DWORD size,flags,height,width;long pitch;DWORD backbuffers,mipmaps,alpha,reserved;void*surface;DWORD keys[8];PIXELFORMAT format;DWORD caps;}SURFACEDESC;
typedef struct{WORD tag,channels;DWORD rate,average;WORD align,bits,size;}WAVEFORMAT;
typedef struct{DWORD size,flags,bytes,reserved;WAVEFORMAT*format;DWORD algorithm;}DSBUFFERDESC;
typedef struct{DWORD size,status,user;BYTE*source;DWORD source_length,source_used,source_user;BYTE*destination;DWORD destination_length,destination_used,destination_user,reserved[10];}ACMHEADER;
typedef LONG(WINAPI*WNDPROC)(void*,DWORD,DWORD,LONG);typedef struct{DWORD style;WNDPROC proc;int cls_extra,win_extra;void*instance,*icon,*cursor,*background;const char*menu,*name;}WNDCLASSA32;
__attribute__((dllimport))HANDLE WINAPI GetStdHandle(DWORD);__attribute__((dllimport))BOOL WINAPI WriteFile(HANDLE,const void*,DWORD,DWORD*,void*);__attribute__((dllimport))void WINAPI ExitProcess(DWORD);
__attribute__((dllimport))void* WINAPI LoadLibraryA(const char*);__attribute__((dllimport))void* WINAPI GetProcAddress(void*,const char*);__attribute__((dllimport))BOOL WINAPI FreeLibrary(void*);
__attribute__((dllimport))int WINAPI WSAStartup(WORD,WSADATA32*);__attribute__((dllimport))int WINAPI WSACleanup(void);__attribute__((dllimport))SOCKET WINAPI socket(int,int,int);__attribute__((dllimport))int WINAPI closesocket(SOCKET);__attribute__((dllimport))int WINAPI bind(SOCKET,const SOCKADDR32*,int);__attribute__((dllimport))int WINAPI listen(SOCKET,int);__attribute__((dllimport))SOCKET WINAPI accept(SOCKET,SOCKADDR32*,int*);__attribute__((dllimport))int WINAPI sendto(SOCKET,const char*,int,int,const SOCKADDR32*,int);__attribute__((dllimport))int WINAPI recvfrom(SOCKET,char*,int,int,SOCKADDR32*,int*);__attribute__((dllimport))int WINAPI ioctlsocket(SOCKET,DWORD,DWORD*);__attribute__((dllimport))DWORD WINAPI inet_addr(const char*);__attribute__((dllimport))WORD WINAPI htons(WORD);
__attribute__((dllimport))BOOL WINAPI SHGetSpecialFolderPathA(void*,char*,int,BOOL);__attribute__((dllimport))void* WINAPI ImageList_Create(int,int,DWORD,int,int);__attribute__((dllimport))BOOL WINAPI ImageList_Destroy(void*);
__attribute__((dllimport))BOOL WINAPI SystemTimeToFileTime(const SYSTEMTIME32*,FILETIME32*);__attribute__((dllimport))BOOL WINAPI FileTimeToSystemTime(const FILETIME32*,SYSTEMTIME32*);
__attribute__((dllimport))DWORD WINAPI DirectDrawCreate(const void*,void**,void*);__attribute__((dllimport))DWORD WINAPI DirectSoundCreate(const void*,void**,void*);__attribute__((dllimport))int WINAPI GetExpandedNameA(const char*,char*);
__attribute__((dllimport))void* WINAPI InternetOpenA(const char*,DWORD,const char*,const char*,DWORD);__attribute__((dllimport))BOOL WINAPI InternetCloseHandle(void*);
__attribute__((dllimport))DWORD WINAPI acmGetVersion(void);__attribute__((dllimport))DWORD WINAPI acmStreamOpen(void**,void*,const WAVEFORMAT*,const WAVEFORMAT*,void*,DWORD,DWORD,DWORD);__attribute__((dllimport))DWORD WINAPI acmStreamPrepareHeader(void*,ACMHEADER*,DWORD);__attribute__((dllimport))DWORD WINAPI acmStreamConvert(void*,ACMHEADER*,DWORD);__attribute__((dllimport))DWORD WINAPI acmStreamClose(void*,DWORD);__attribute__((dllimport))void WINAPI AVIFileInit(void);__attribute__((dllimport))void WINAPI AVIFileExit(void);__attribute__((dllimport))DWORD WINAPI WNetGetUserA(const char*,char*,DWORD*);
__attribute__((dllimport))WORD WINAPI RegisterClassA(const WNDCLASSA32*);__attribute__((dllimport))void*WINAPI CreateWindowExA(DWORD,const char*,const char*,DWORD,int,int,int,int,void*,void*,void*,void*);__attribute__((dllimport))LONG WINAPI SendMessageA(void*,DWORD,DWORD,LONG);__attribute__((dllimport))BOOL WINAPI DestroyWindow(void*);__attribute__((dllimport))LONG WINAPI DefWindowProcA(void*,DWORD,DWORD,LONG);
__attribute__((dllimport))void* WINAPI GetLastActivePopup(void*);__attribute__((dllimport))void* WINAPI DdeClientTransaction(BYTE*,DWORD,void*,void*,DWORD,DWORD,DWORD,DWORD*);
static void out(const char*s){DWORD n=0,l=0;while(s[l])l++;WriteFile(GetStdHandle(STD_OUTPUT_HANDLE),s,l,&n,0);}static void fail(DWORD code){out("[WIN95COMPAT2] FAIL\n");ExitProcess(code);}
static void test_directx(void){void*dd=0,*surface=0,*ds=0,*buffer=0,*p1=0,*p2=0;DWORD n1=0,n2=0;void**v;SURFACEDESC sd;DSBUFFERDESC bd;WAVEFORMAT wf={1,1,11025,11025,1,8,0};for(DWORD i=0;i<sizeof(sd);i++)((BYTE*)&sd)[i]=0;sd.size=sizeof(sd);sd.flags=1|2|4|0x1000;sd.width=32;sd.height=32;sd.format.size=sizeof(sd.format);sd.format.flags=0x40|0x20;sd.format.rgb_bits=8;sd.caps=0x40;if(DirectDrawCreate(0,&dd,0)!=0||!dd)fail(20);v=*(void***)dd;if(((DWORD(WINAPI*)(void*,SURFACEDESC*,void**,void*))v[6])(dd,&sd,&surface,0)!=0||!surface)fail(21);v=*(void***)surface;if(((DWORD(WINAPI*)(void*,void*,SURFACEDESC*,DWORD,void*))v[25])(surface,0,&sd,0,0)!=0||!sd.surface)fail(22);((BYTE*)sd.surface)[0]=7;if(((DWORD(WINAPI*)(void*,void*))v[32])(surface,sd.surface)!=0)fail(23);((DWORD(WINAPI*)(void*))v[2])(surface);v=*(void***)dd;((DWORD(WINAPI*)(void*))v[2])(dd);if(DirectSoundCreate(0,&ds,0)!=0||!ds)fail(24);bd.size=sizeof(bd);bd.flags=0;bd.bytes=256;bd.reserved=0;bd.format=&wf;bd.algorithm=0;v=*(void***)ds;if(((DWORD(WINAPI*)(void*,DSBUFFERDESC*,void**,void*))v[3])(ds,&bd,&buffer,0)!=0||!buffer)fail(25);v=*(void***)buffer;if(((DWORD(WINAPI*)(void*,DWORD,DWORD,void**,DWORD*,void**,DWORD*,DWORD))v[11])(buffer,0,256,&p1,&n1,&p2,&n2,0)!=0||!p1||n1==0)fail(26);for(DWORD i=0;i<n1;i++)((BYTE*)p1)[i]=128;if(((DWORD(WINAPI*)(void*,void*,DWORD,void*,DWORD))v[19])(buffer,p1,n1,p2,n2)!=0)fail(27);((DWORD(WINAPI*)(void*))v[2])(buffer);v=*(void***)ds;((DWORD(WINAPI*)(void*))v[2])(ds);}
static void test_acm(void){WAVEFORMAT src={1,1,8000,8000,1,8,0},dst={1,1,16000,32000,2,16,0};BYTE in[8]={0,32,64,96,128,160,192,255},output[32];ACMHEADER h;void*stream=0;for(DWORD i=0;i<sizeof(h);i++)((BYTE*)&h)[i]=0;h.size=sizeof(h);h.source=in;h.source_length=sizeof(in);h.destination=output;h.destination_length=sizeof(output);if(acmStreamOpen(&stream,0,&src,&dst,0,0,0,0)!=0||!stream)fail(30);if(acmStreamPrepareHeader(stream,&h,0)!=0||acmStreamConvert(stream,&h,0)!=0||h.source_used!=8||h.destination_used==0)fail(31);if(acmStreamClose(stream,0)!=0)fail(32);}
static void test_controls(void){WNDCLASSA32 wc={0,DefWindowProcA,0,0,0,0,0,0,0,"BK95TEST"};void*parent,*list,*combo,*progress;char text[16];if(!RegisterClassA(&wc))fail(40);parent=CreateWindowExA(0,"BK95TEST","Controls",0,10,10,240,180,0,0,0,0);if(!parent)fail(41);if(GetLastActivePopup(parent)!=parent)fail(46);if(DdeClientTransaction(0,0,0,0,0,0,0,0)!=0)fail(47);list=CreateWindowExA(0,"LISTBOX","",0x50000000,5,5,100,80,parent,(void*)101,0,0);combo=CreateWindowExA(0,"COMBOBOX","",0x50000000,110,5,100,24,parent,(void*)102,0,0);progress=CreateWindowExA(0,"msctls_progress32","",0x50000000,5,95,205,18,parent,(void*)103,0,0);if(!list||!combo||!progress)fail(42);if(SendMessageA(list,0x180,0,(LONG)"Uno")!=0||SendMessageA(list,0x180,0,(LONG)"Dos")!=1||SendMessageA(list,0x18B,0,0)!=2||SendMessageA(list,0x186,1,0)!=1||SendMessageA(list,0x188,0,0)!=1)fail(43);if(SendMessageA(list,0x189,1,(LONG)text)!=3||text[0]!='D')fail(44);if(SendMessageA(combo,0x143,0,(LONG)"A")!=0||SendMessageA(combo,0x143,0,(LONG)"B")!=1||SendMessageA(combo,0x14E,0,0)!=0)fail(45);SendMessageA(progress,0x0401,0,(LONG)(100UL<<16));SendMessageA(progress,0x0402,75,0);DestroyWindow(parent);}
void entry(void){WSADATA32 data;SOCKET s,u;SOCKADDR32 local={2,0,{0,0,0,0},{0}},remote={2,0,{255,255,255,255},{0}};char path[260],expanded[260],user[16],packet='X';DWORD user_size=sizeof(user),one=1;int remote_size=sizeof(remote);void*list,*inet,*shell;SYSTEMTIME32 st={1998,6,0,25,12,30,15,0},back;FILETIME32 ft;shell=LoadLibraryA("SHELL32");if(!shell||!GetProcAddress(shell,"DragAcceptFiles")||!FreeLibrary(shell))fail(17);if(WSAStartup(0x0101,&data)!=0)fail(1);if(inet_addr("127.0.0.1")!=0x0100007FU||htons(80)!=0x5000U)fail(2);s=socket(2,1,6);if(s==0xFFFFFFFFU)fail(3);local.port=htons(27991);if(bind(s,&local,sizeof(local))!=0||listen(s,2)!=0)fail(4);if(ioctlsocket(s,0x8004667EUL,&one)!=0||accept(s,0,0)!=0xFFFFFFFFU)fail(5);u=socket(2,2,17);local.port=htons(27992);if(u==0xFFFFFFFFU||bind(u,&local,sizeof(local))!=0)fail(6);remote.port=htons(27992);if(sendto(u,&packet,1,0,&remote,sizeof(remote))!=1)fail(7);if(ioctlsocket(u,0x8004667EUL,&one)!=0)fail(8);(void)recvfrom(u,&packet,1,0,&remote,&remote_size);if(closesocket(u)!=0||closesocket(s)!=0||WSACleanup()!=0)fail(9);if(!SHGetSpecialFolderPathA(0,path,2,0)||path[0]!='C')fail(10);list=ImageList_Create(16,16,0,1,1);if(!list||!ImageList_Destroy(list))fail(11);if(!SystemTimeToFileTime(&st,&ft)||!FileTimeToSystemTime(&ft,&back)||back.year!=1998||back.month!=6||back.day!=25)fail(12);if(GetExpandedNameA("C:\\TEST.EX_",expanded)<0||expanded[0]!='C')fail(13);inet=InternetOpenA("BlesKernOS Win95",0,0,0,0);if(!inet||!InternetCloseHandle(inet))fail(14);if(acmGetVersion()!=0x04030000U)fail(15);AVIFileInit();AVIFileExit();if(WNetGetUserA(0,user,&user_size)!=0||user[0]!='U')fail(16);test_directx();test_acm();test_controls();out("Win95 media/network/control compatibility OK!\n");ExitProcess(0);}
